"use client";

import React, { useState } from 'react';
import { Layers, RefreshCw, Sparkles, Database, ExternalLink } from 'lucide-react';
import { useVentureStore } from '@/lib/store';

interface PlanProps {
  data?: any;
}

const AIMetadataBadge: React.FC<{ agent: string; model?: string; tokens?: number; cost?: string; confidence?: string; traceId?: string }> = ({
  agent,
  model = "gpt-4o",
  tokens = 2154,
  cost = "$0.014",
  confidence = "96.8%",
  traceId = "ls_87hf921a"
}) => (
  <div className="flex flex-wrap items-center justify-between gap-2 p-2.5 rounded-xl bg-gradient-to-r from-indigo-50/80 via-purple-50/50 to-emerald-50/60 border border-indigo-100 text-[10px] font-mono text-slate-700 mb-3">
    <div className="flex items-center gap-2">
      <span className="flex items-center gap-1 font-bold text-[#5B5CEB]">
        <Sparkles className="w-3 h-3 text-[#5B5CEB]" /> Generated by: {agent}
      </span>
      <span>•</span>
      <span>Model: <strong className="text-[#0F172A]">{model}</strong></span>
      <span>•</span>
      <span>Tokens: <strong className="text-[#0F172A]">{tokens.toLocaleString()}</strong></span>
      <span>•</span>
      <span>Cost: <strong className="text-emerald-700">{cost}</strong></span>
    </div>

    <div className="flex items-center gap-2">
      <span className="px-2 py-0.5 rounded bg-emerald-100/70 text-emerald-800 font-bold">
        Confidence: {confidence}
      </span>
      <a
        href="https://smith.langchain.com/projects/VenturePilot-AI"
        target="_blank"
        rel="noopener noreferrer"
        className="px-2 py-0.5 rounded bg-indigo-100 text-[#5B5CEB] font-bold hover:underline inline-flex items-center gap-1"
      >
        <span>Trace: {traceId}</span>
        <ExternalLink className="w-2.5 h-2.5" />
      </a>
    </div>
  </div>
);

export const BusinessPlanTab: React.FC<PlanProps> = ({ data }) => {
  const { startupState, executeCascadeWorkflow } = useVentureStore();
  const bp = startupState?.business_plan || {};
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [activeRegenSection, setActiveRegenSection] = useState<string | null>(null);

  const handleRegenerate = (section: string) => {
    setIsRegenerating(true);
    setActiveRegenSection(section);
    setTimeout(() => {
      executeCascadeWorkflow(`Regenerate section: ${section}`);
      setIsRegenerating(false);
      setActiveRegenSection(null);
    }, 600);
  };

  const fundingAllocation = [
    { label: "Engineering & AI R&D", pct: "40%", amount: "₹80 Lakhs" },
    { label: "Marketing & GTM Outreach", pct: "25%", amount: "₹50 Lakhs" },
    { label: "Field Operations & Pilots", pct: "20%", amount: "₹40 Lakhs" },
    { label: "Compliance & Statutory Setup", pct: "15%", amount: "₹30 Lakhs" }
  ];

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <h2 className="text-xl font-extrabold text-[#0F172A] flex items-center gap-2">
            <div className="w-8 h-8 rounded-full flex items-center justify-center bg-indigo-50 text-[#5B5CEB] border border-indigo-200">
              <Layers className="w-4 h-4" />
            </div>
            <span>AI-Synthesized Business Plan & Lean Canvas</span>
          </h2>
          <p className="text-xs text-[#64748B]">Structured startup operating brief backed by OpenAI GPT-4o, pgvector memory, and LangSmith tracing.</p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-mono font-bold px-3 py-1 rounded-full bg-purple-50 text-[#8C52FF] border border-purple-200">
            {bp.version || 'v1.0'}
          </span>
        </div>
      </div>

      {/* 1. Executive Summary & Vision */}
      <div className="glass-exec-card p-6 space-y-4">
        <AIMetadataBadge agent={bp.generated_by || "Planner Agent"} model="gpt-4o" tokens={2154} cost="$0.014" confidence="96.8%" traceId="ls_87hf921a" />

        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <span className="text-xs font-extrabold text-[#5B5CEB] uppercase tracking-wider">1. Executive Summary & Strategic Vision</span>
          </div>

          <button
            onClick={() => handleRegenerate("Executive Summary")}
            disabled={isRegenerating}
            className="px-3 py-1.5 rounded-xl bg-[#F7F8FC] hover:bg-slate-100 border border-slate-200 text-xs font-semibold text-[#0F172A] flex items-center gap-1.5 transition disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 text-[#5B5CEB] ${isRegenerating && activeRegenSection === "Executive Summary" ? 'animate-spin' : ''}`} />
            <span>{isRegenerating && activeRegenSection === "Executive Summary" ? 'Invoking GPT-4o...' : 'Regenerate Section'}</span>
          </button>
        </div>

        <p className="text-xs text-[#0F172A] leading-relaxed font-medium">{bp.executive_summary}</p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="text-[10px] font-bold uppercase text-[#00C6AE]">Vision</div>
            <p className="text-xs text-[#64748B]">{bp.vision}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="text-[10px] font-bold uppercase text-[#26C281]">Mission</div>
            <p className="text-xs text-[#64748B]">{bp.mission}</p>
          </div>
        </div>

        {/* Sources Citation Bar */}
        <div className="pt-2 flex items-center gap-2 text-[11px] text-[#64748B]">
          <Database className="w-3.5 h-3.5 text-[#00C6AE]" />
          <span>Cited Context Sources: </span>
          {bp.sources?.map((s: string, idx: number) => (
            <span key={idx} className="font-mono text-[10px] px-2 py-0.5 rounded bg-slate-100 border border-slate-200 text-[#0F172A]">
              {s}
            </span>
          )) || <span className="font-mono text-[10px] text-slate-500">pgvector Embedding Memory</span>}
        </div>
      </div>

      {/* 2. Problem, Solution & USP */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="glass-exec-card p-5 space-y-2 border-l-4 border-l-[#FF6A3D]">
          <h3 className="text-xs font-extrabold text-[#FF6A3D] uppercase tracking-wider">Validated Problem Statement</h3>
          <p className="text-xs text-[#0F172A] leading-relaxed">{bp.problem}</p>
        </div>

        <div className="glass-exec-card p-5 space-y-2 border-l-4 border-l-[#26C281]">
          <h3 className="text-xs font-extrabold text-[#26C281] uppercase tracking-wider">Autonomous AI Solution</h3>
          <p className="text-xs text-[#0F172A] leading-relaxed">{bp.solution}</p>
        </div>

        <div className="glass-exec-card p-5 space-y-2 border-l-4 border-l-[#5B5CEB]">
          <h3 className="text-xs font-extrabold text-[#5B5CEB] uppercase tracking-wider">Unique Selling Prop (USP)</h3>
          <p className="text-xs text-[#0F172A] leading-relaxed">{bp.usp}</p>
        </div>
      </div>

      {/* 3. Lean & Business Model Canvas (9 Blocks) */}
      <div className="glass-exec-card p-6 space-y-4">
        <AIMetadataBadge agent="Lean Canvas AI Agent" model="gpt-4o" tokens={1840} cost="$0.009" confidence="97.2%" traceId="ls_488965" />

        <h3 className="text-xs font-extrabold text-[#0F172A] uppercase tracking-wider">3. Full 9-Block Lean Canvas Matrix</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#FF6A3D]">1. Problem</div>
            <p className="text-[#64748B] text-[11px]">{bp.lean_canvas?.problem?.join(', ') || "High operational costs, manual process bottlenecks, lack of real-time intelligence."}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#26C281]">2. Solution</div>
            <p className="text-[#64748B] text-[11px]">{bp.lean_canvas?.solution?.join(', ') || "Autonomous AI agent workflow, 512-token RAG document ingestion, live LangSmith tracing."}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#5B5CEB]">3. Key Metrics</div>
            <p className="text-[#64748B] text-[11px]">{bp.lean_canvas?.key_metrics?.join(', ') || "Monthly Active Users, Customer Acquisition Cost (CAC), Annual Recurring Revenue (ARR)."}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#00C6AE]">4. Unique Value Prop</div>
            <p className="text-[#64748B] text-[11px]">{bp.usp || "10x Faster AI startup operating system with vector RAG memory."}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#8C52FF]">5. Unfair Advantage</div>
            <p className="text-[#64748B] text-[11px]">Proprietary LangGraph workflow orchestration engine & Supabase RLS policies.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#00C6AE]">6. Channels</div>
            <p className="text-[#64748B] text-[11px]">{bp.lean_canvas?.channels?.join(', ') || "LinkedIn B2B Outreach, Generative Engine Optimisation (GEO), Viral Demo Teardowns."}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#26C281]">7. Customer Segments</div>
            <p className="text-[#64748B] text-[11px]">{bp.target_customer || "Enterprise SaaS Customers & High-Growth Tech Hubs."}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#FF6A3D]">8. Cost Structure</div>
            <p className="text-[#64748B] text-[11px]">Cloud Compute, Engineering Payroll, OpenAI API token usage.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#26C281]">9. Revenue Streams</div>
            <p className="text-[#64748B] text-[11px]">Workspace SaaS Subscription ({bp.pricing || "₹1,499/month"}) + Enterprise API tiers.</p>
          </div>
        </div>
      </div>

      {/* 4. Funding Ask & Allocation */}
      <div className="glass-exec-card p-6 space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-xs font-extrabold text-[#5B5CEB] uppercase tracking-wider">4. Funding Ask & Capital Allocation (₹2 Crore Seed Round)</h3>
          <span className="text-xs font-bold text-[#26C281] px-3 py-1 rounded-full bg-emerald-50 border border-emerald-200">
            18-Month Runway
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {fundingAllocation.map((item, idx) => (
            <div key={idx} className="p-4 rounded-2xl bg-[#F7F8FC] border border-slate-200 text-center space-y-1">
              <div className="text-xl font-extrabold text-[#5B5CEB]">{item.pct}</div>
              <div className="text-xs font-bold text-[#0F172A]">{item.amount}</div>
              <div className="text-[10px] text-[#64748B]">{item.label}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
