"use client";

import React, { useState } from 'react';
import { Layers, CheckCircle2, ShieldCheck, DollarSign, Target, Award, Users, AlertTriangle, FileText, RefreshCw, Sparkles, Database } from 'lucide-react';
import { useVentureStore } from '@/lib/store';

interface PlanProps {
  data?: any;
}

export const BusinessPlanTab: React.FC<PlanProps> = ({ data }) => {
  const { startupState, executeCascadeWorkflow } = useVentureStore();
  const bp = startupState?.business_plan || {};
  const [isRegenerating, setIsRegenerating] = useState(false);

  const handleRegenerate = (section: string) => {
    setIsRegenerating(true);
    setTimeout(() => {
      executeCascadeWorkflow(`Regenerate section: ${section}`);
      setIsRegenerating(false);
    }, 500);
  };

  const fundingAllocation = [
    { label: "Engineering & AI R&D", pct: "40%", amount: "₹80 Lakhs" },
    { label: "Marketing & FPO Outreach", pct: "25%", amount: "₹50 Lakhs" },
    { label: "Field Pilot Operations", pct: "20%", amount: "₹40 Lakhs" },
    { label: "Compliance & Statutory Setup", pct: "15%", amount: "₹30 Lakhs" }
  ];

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <h2 className="text-xl font-extrabold text-[#0F172A] flex items-center gap-2">
            <div className="w-8 h-8 rounded-full flex items-center justify-center icon-pill-primary">
              <Layers className="w-4 h-4" />
            </div>
            <span>Notion-Style Investor Business Plan</span>
          </h2>
          <p className="text-xs text-[#64748B]">Multi-section document backed by vector memory with agent metadata and dynamic section regeneration.</p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-mono font-bold px-3 py-1 rounded-full bg-purple-50 text-[#8C52FF] border border-purple-200">
            Version {bp.version || 'v3.1'}
          </span>
        </div>
      </div>

      {/* 1. Executive Summary & Vision */}
      <div className="glass-exec-card p-6 space-y-4">
        <div className="flex items-center justify-between border-b border-slate-100 pb-3">
          <div className="flex items-center gap-2">
            <span className="text-xs font-extrabold text-[#7C5CFF] uppercase tracking-wider">1. Executive Summary & Vision</span>
            <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 text-[#64748B] font-semibold">
              Generated by: {bp.generated_by || 'Research Agent'}
            </span>
          </div>

          <button
            onClick={() => handleRegenerate("Executive Summary")}
            disabled={isRegenerating}
            className="px-3 py-1 rounded-xl bg-[#F7F8FC] hover:bg-slate-100 border border-slate-200 text-xs font-semibold text-[#0F172A] flex items-center gap-1.5 transition"
          >
            <RefreshCw className={`w-3.5 h-3.5 text-[#5B5CEB] ${isRegenerating ? 'animate-spin' : ''}`} />
            <span>Regenerate Section</span>
          </button>
        </div>

        <p className="text-xs text-[#0F172A] leading-relaxed font-medium">{bp.executive_summary}</p>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-2">
          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="text-[10px] font-bold uppercase text-[#00C6AE]">Vision</div>
            <p className="text-xs text-[#64748B]">{bp.vision}</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="text-[10px] font-bold uppercase text-[#26C281]">Mission</div>
            <p className="text-xs text-[#64748B]">{bp.mission}</p>
          </div>
        </div>

        {/* Sources Citation Bar */}
        <div className="pt-2 flex items-center gap-2 text-[11px] text-[#64748B]">
          <Database className="w-3.5 h-3.5 text-[#00C6AE]" />
          <span>Cited Sources: </span>
          {bp.sources?.map((s: string, idx: number) => (
            <span key={idx} className="font-mono text-[10px] px-2 py-0.5 rounded bg-slate-100 border border-slate-200 text-[#0F172A]">
              {s}
            </span>
          ))}
        </div>
      </div>

      {/* 2. Problem, Solution & USP */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="glass-exec-card p-5 space-y-2 border-l-4 border-l-[#FF6A3D]">
          <h3 className="text-xs font-extrabold text-[#FF6A3D] uppercase tracking-wider">Problem Statement</h3>
          <p className="text-xs text-[#0F172A] leading-relaxed">{bp.problem}</p>
        </div>

        <div className="glass-exec-card p-5 space-y-2 border-l-4 border-l-[#26C281]">
          <h3 className="text-xs font-extrabold text-[#26C281] uppercase tracking-wider">AI Solution</h3>
          <p className="text-xs text-[#0F172A] leading-relaxed">{bp.solution}</p>
        </div>

        <div className="glass-exec-card p-5 space-y-2 border-l-4 border-l-[#5B5CEB]">
          <h3 className="text-xs font-extrabold text-[#5B5CEB] uppercase tracking-wider">Unique Selling Prop (USP)</h3>
          <p className="text-xs text-[#0F172A] leading-relaxed">{bp.usp}</p>
        </div>
      </div>

      {/* 3. Lean & Business Model Canvas (9 Blocks) */}
      <div className="glass-exec-card p-6 space-y-4">
        <h3 className="text-xs font-extrabold text-[#0F172A] uppercase tracking-wider">3. Full 9-Block Lean Canvas Matrix</h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#FF6A3D]">1. Problem</div>
            <p className="text-[#64748B] text-[11px]">Late pest detection, unpriced yields, fragmented rural market access.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#26C281]">2. Solution</div>
            <p className="text-[#64748B] text-[11px]">Autonomous LangGraph AI agronomy agent + IoT soil sensors.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#5B5CEB]">3. Key Metrics</div>
            <p className="text-[#64748B] text-[11px]">FPOs Onboarded, Monthly ARR (₹), Crop Yield Accuracy (%).</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#00C6AE]">4. Unique Value Prop</div>
            <p className="text-[#64748B] text-[11px]">10x Faster AI yield diagnostics in regional Indian languages.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#8C52FF]">5. Unfair Advantage</div>
            <p className="text-[#64748B] text-[11px]">Proprietary vector agronomy RAG memory store & WhatsApp UI.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#00C6AE]">6. Channels</div>
            <p className="text-[#64748B] text-[11px]">Direct FPO Outreach, Kisan Vikas Kendras (KVKs), WhatsApp API.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#26C281]">7. Customer Segments</div>
            <p className="text-[#64748B] text-[11px]">Indian FPOs (500+ members), Agritech Cooperatives & Exporters.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#FF6A3D]">8. Cost Structure</div>
            <p className="text-[#64748B] text-[11px]">Cloud Compute, Engineering Payroll, Field Pilot Demonstrations.</p>
          </div>

          <div className="p-3.5 rounded-2xl bg-[#F7F8FC] border border-slate-200 space-y-1">
            <div className="font-bold text-[#26C281]">9. Revenue Streams</div>
            <p className="text-[#64748B] text-[11px]">FPO SaaS Subscription (₹1,499/mo) + Marketplace Commission.</p>
          </div>
        </div>
      </div>

      {/* 4. Funding Ask & Allocation (₹2 Cr Seed Funding) */}
      <div className="glass-exec-card p-6 space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-xs font-extrabold text-[#5B5CEB] uppercase tracking-wider">4. Funding Ask & Capital Allocation (₹2 Crore Seed Round)</h3>
          <span className="text-xs font-bold text-[#26C281] px-3 py-1 rounded-full bg-emerald-50 border border-emerald-200">
            18-Month Runway
          </span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {fundingAllocation.map((item, idx) => (
            <div key={idx} className="p-4 rounded-2xl bg-[#F7F8FC] border border-slate-200 text-center space-y-1">
              <div className="text-xl font-extrabold text-[#5B5CEB]">{item.pct}</div>
              <div className="text-xs font-bold text-[#0F172A]">{item.amount}</div>
              <div className="text-[10px] text-[#64748B]">{item.label}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
