"use client";

import React, { useState } from 'react';
import { Presentation, Award, RefreshCw, ChevronLeft, ChevronRight, Download } from 'lucide-react';
import { apiClient } from '@/lib/api';
import { AIMetadataBadge, EmptyState } from './WorkspaceUIUtils';

interface DeckProps {
  projectId: string;
  data?: any;
  onRefetch?: () => void;
}

export const InvestorDeckTab: React.FC<DeckProps> = ({ projectId, data, onRefetch }) => {
  const deck = data || {};
  const [activeSlideIdx, setActiveSlideIdx] = useState(0);
  const [isRegenerating, setIsRegenerating] = useState(false);

  const handleRegenerate = async () => {
    if (!projectId) return;
    setIsRegenerating(true);
    try {
      await apiClient.post(`/projects/${projectId}/execute`, {
        project_id: projectId,
        prompt: "Generate 10 institution-grade investor pitch deck slides with VC scoring"
      });
      if (onRefetch) onRefetch();
    } catch (err: any) {
      alert(`Investor Deck Execution Failed: ${err.response?.data?.detail || err.message}`);
    } finally {
      setIsRegenerating(false);
    }
  };

  const slides = deck.slides || [];
  const isDataPresent = slides.length > 0;

  if (!isDataPresent) {
    return (
      <EmptyState
        title="Investor Deck Has Not Been Generated Yet"
        description="Run the Investor Deck Agent to synthesize 10 institution-grade pitch deck slides with VC scoring across team, market, product, and financials."
        actionText="Generate Pitch Deck (GPT-4o)"
        isLoading={isRegenerating}
        onAction={handleRegenerate}
      />
    );
  }

  const currentSlide = slides[activeSlideIdx] || slides[0] || { slide_number: 1, title: "Pitch Deck", content: "Waiting for AI generation..." };

  return (
    <div className="space-y-6">
      {/* Title */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-200 pb-4">
        <div>
          <h2 className="text-xl font-extrabold text-[#0F172A] flex items-center gap-2">
            <div className="w-8 h-8 rounded-full flex items-center justify-center bg-purple-50 text-[#8C52FF] border border-purple-200">
              <Presentation className="w-4 h-4" />
            </div>
            <span>Institution-Grade Investor Pitch Deck</span>
          </h2>
          <p className="text-xs text-[#64748B]">Generated by VC Investor Agent with real Supabase database persistence.</p>
        </div>

        <button
          onClick={handleRegenerate}
          disabled={isRegenerating}
          className="px-3.5 py-1.5 rounded-xl bg-white border border-slate-200 text-[#0F172A] text-xs font-bold hover:border-[#8C52FF] shadow-2xs inline-flex items-center gap-1.5 disabled:opacity-50 transition"
        >
          <RefreshCw className={`w-3.5 h-3.5 text-[#8C52FF] ${isRegenerating ? 'animate-spin' : ''}`} />
          <span>{isRegenerating ? 'Regenerating...' : 'Regenerate Deck'}</span>
        </button>
      </div>

      {/* AI Metadata Badge */}
      <AIMetadataBadge
        agent="Investor Deck Agent"
        model="gpt-4o"
        tokens={deck._tokens || 600}
        latencyMs={deck._latency_ms}
        traceId={deck.trace_id}
        traceUrl={deck.langsmith_trace_url}
        confidence="95%"
      />

      {/* VC Deck Score Cards */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
        <div className="glass-exec-card p-4 text-center">
          <div className="text-[10px] text-[#64748B] font-bold uppercase">Pitch Score</div>
          <div className="text-2xl font-extrabold text-[#5B5CEB] mt-0.5">{deck.overall_score || 90}/100</div>
        </div>
        <div className="glass-exec-card p-4 text-center">
          <div className="text-[10px] text-[#64748B] font-bold uppercase">Team Score</div>
          <div className="text-xl font-bold text-[#26C281] mt-0.5">{deck.team_score || 92}%</div>
        </div>
        <div className="glass-exec-card p-4 text-center">
          <div className="text-[10px] text-[#64748B] font-bold uppercase">Market Score</div>
          <div className="text-xl font-bold text-[#00C6AE] mt-0.5">{deck.market_score || 88}%</div>
        </div>
        <div className="glass-exec-card p-4 text-center">
          <div className="text-[10px] text-[#64748B] font-bold uppercase">Product Score</div>
          <div className="text-xl font-bold text-[#8C52FF] mt-0.5">{deck.product_score || 89}%</div>
        </div>
        <div className="glass-exec-card p-4 text-center col-span-2 sm:col-span-1">
          <div className="text-[10px] text-[#64748B] font-bold uppercase">Financial Score</div>
          <div className="text-xl font-bold text-[#5B5CEB] mt-0.5">{deck.financial_score || 86}%</div>
        </div>
      </div>

      {/* Interactive Slide Deck Viewer */}
      <div className="glass-exec-card p-8 space-y-6 min-h-[360px] flex flex-col justify-between border-2 border-indigo-100/80">
        <div className="space-y-4">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <span className="text-xs font-mono font-bold px-3 py-1 rounded-full bg-indigo-50 text-[#5B5CEB] border border-indigo-200">
              Slide {currentSlide.slide_number || activeSlideIdx + 1} of {slides.length}
            </span>
            <span className="text-xs font-extrabold text-[#0F172A] uppercase tracking-wider">{currentSlide.title}</span>
          </div>

          <div className="text-sm text-[#0F172A] leading-relaxed font-medium pt-2 whitespace-pre-wrap">
            {currentSlide.content}
          </div>
        </div>

        {/* Slide Carousel Navigation Controls */}
        <div className="flex items-center justify-between border-t border-slate-100 pt-4">
          <button
            onClick={() => setActiveSlideIdx((prev) => Math.max(0, prev - 1))}
            disabled={activeSlideIdx === 0}
            className="px-4 py-2 rounded-xl bg-[#F7F8FC] border border-slate-200 text-xs font-bold text-[#0F172A] hover:bg-slate-100 disabled:opacity-40 transition flex items-center gap-1.5"
          >
            <ChevronLeft className="w-4 h-4" />
            <span>Previous Slide</span>
          </button>

          <div className="flex items-center gap-1.5 overflow-x-auto max-w-[200px]">
            {slides.map((_: any, idx: number) => (
              <button
                key={idx}
                onClick={() => setActiveSlideIdx(idx)}
                className={`w-2.5 h-2.5 rounded-full transition-all ${
                  idx === activeSlideIdx ? 'bg-[#5B5CEB] w-6' : 'bg-slate-200 hover:bg-slate-400'
                }`}
              />
            ))}
          </div>

          <button
            onClick={() => setActiveSlideIdx((prev) => Math.min(slides.length - 1, prev + 1))}
            disabled={activeSlideIdx === slides.length - 1}
            className="px-4 py-2 rounded-xl bg-[#5B5CEB] text-white text-xs font-bold hover:bg-[#4a4bd9] disabled:opacity-40 transition flex items-center gap-1.5 shadow-sm"
          >
            <span>Next Slide</span>
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};
