"use client";

import React from 'react';
import { Sparkles, ExternalLink, Bot, AlertCircle, RefreshCw } from 'lucide-react';

interface AIMetadataBadgeProps {
  agent: string;
  model?: string;
  tokens?: number;
  latencyMs?: number;
  cost?: string;
  confidence?: string;
  traceId?: string | null;
  traceUrl?: string | null;
}

export const AIMetadataBadge: React.FC<AIMetadataBadgeProps> = ({
  agent,
  model = "gpt-4o",
  tokens,
  latencyMs,
  cost,
  confidence,
  traceId,
  traceUrl
}) => {
  const displayUrl = traceUrl || (traceId ? `https://smith.langchain.com/projects/p/VenturePilot-AI/r/${traceId}` : null);
  const displayTrace = traceId ? (traceId.length > 16 ? `${traceId.slice(0, 14)}...` : traceId) : "VenturePilot-AI";

  return (
    <div className="flex flex-wrap items-center justify-between gap-2 p-2.5 rounded-xl bg-gradient-to-r from-indigo-50/80 via-purple-50/50 to-emerald-50/60 border border-indigo-100 text-[10px] font-mono text-slate-700 mb-3">
      <div className="flex items-center gap-2 flex-wrap">
        <span className="flex items-center gap-1 font-bold text-[#5B5CEB]">
          <Sparkles className="w-3 h-3 text-[#5B5CEB]" /> Generated by: {agent}
        </span>
        <span>•</span>
        <span>Model: <strong className="text-[#0F172A]">{model}</strong></span>
        {tokens !== undefined && (
          <>
            <span>•</span>
            <span>Tokens: <strong className="text-[#0F172A]">{tokens.toLocaleString()}</strong></span>
          </>
        )}
        {latencyMs !== undefined && (
          <>
            <span>•</span>
            <span>Latency: <strong className="text-[#0F172A]">{latencyMs}ms</strong></span>
          </>
        )}
        {cost && (
          <>
            <span>•</span>
            <span>Cost: <strong className="text-emerald-700">{cost}</strong></span>
          </>
        )}
      </div>

      <div className="flex items-center gap-2">
        {confidence && (
          <span className="px-2 py-0.5 rounded bg-emerald-100/70 text-emerald-800 font-bold">
            Confidence: {confidence}
          </span>
        )}
        {displayUrl ? (
          <a
            href={displayUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="px-2 py-0.5 rounded bg-indigo-100 text-[#5B5CEB] font-bold hover:underline inline-flex items-center gap-1"
          >
            <span>Trace: {displayTrace}</span>
            <ExternalLink className="w-2.5 h-2.5" />
          </a>
        ) : (
          <span className="px-2 py-0.5 rounded bg-slate-100 text-slate-500 font-sans italic text-[9px]">
            LangSmith Tracing: Disabled
          </span>
        )}
      </div>
    </div>
  );
};

interface EmptyStateProps {
  title: string;
  description: string;
  actionText?: string;
  onAction?: () => void;
  isLoading?: boolean;
}

export const EmptyState: React.FC<EmptyStateProps> = ({
  title,
  description,
  actionText = "Execute AI Swarm Pipeline",
  onAction,
  isLoading = false
}) => {
  return (
    <div className="glass-exec-card p-12 text-center space-y-4 my-6">
      <div className="w-14 h-14 rounded-2xl bg-indigo-50 text-[#5B5CEB] border border-indigo-100 flex items-center justify-center mx-auto shadow-sm">
        <Bot className="w-7 h-7" />
      </div>

      <div className="max-w-md mx-auto space-y-1">
        <h3 className="text-base font-extrabold text-[#0F172A]">{title}</h3>
        <p className="text-xs text-[#64748B] leading-relaxed">{description}</p>
      </div>

      {onAction && (
        <button
          onClick={onAction}
          disabled={isLoading}
          className="px-5 py-2.5 rounded-2xl bg-[#5B5CEB] hover:bg-[#4a4bd9] text-white text-xs font-extrabold shadow-md inline-flex items-center gap-2 disabled:opacity-50 transition"
        >
          {isLoading ? (
            <>
              <RefreshCw className="w-4 h-4 animate-spin" />
              <span>Executing AI Workflow...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-4 h-4" />
              <span>{actionText}</span>
            </>
          )}
        </button>
      )}
    </div>
  );
};
